import PageHero from "@/components/page-hero";
import FeatureCard from "@/components/feature-card";
import { Navbar } from "@/components/navbar";
import Footer from "@/components/footer";
import { Button } from "@/components/ui/button";
import Section from "@/components/section";
import type { Metadata } from "next";
import {
  ArrowUpRight,
  CalendarDays,
  Search,
  DollarSign,
  Lightbulb,
  LineChart,
  MailOpen,
  ShoppingCart,
  Users,
  Building2,
  FileDown,
  BarChart3,
  Megaphone,
  ClipboardList,
  Briefcase,
  BedDouble,
  UtensilsCrossed,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Insights | EMS",
  description:
    "Live dashboards that show revenue, engagement and product performance so you can optimise every campaign.",
};

export default function Page() {
  const why = [
    {
      icon: Search,
      title: "No guessing",
      description: "Stop wondering which upsells work.",
    },
    {
      icon: DollarSign,
      title: "Prove ROI",
      description:
        "Show stakeholders the revenue generated by each campaign.",
    },
    {
      icon: Lightbulb,
      title: "Get better",
      description:
        "Use data to refine your messaging and timing.",
    },
  ];

  const see = [
    {
      icon: LineChart,
      title: "Live revenue tracking",
      description:
        "Know how much ancillary you've added today, this week, this month.",
    },
    {
      icon: MailOpen,
      title: "Email performance",
      description:
        "Open rates, click-throughs, and conversions per automation.",
    },
    {
      icon: ShoppingCart,
      title: "Product insights",
      description: "Identify your top-sellers and spot the duds.",
    },
    {
      icon: Users,
      title: "Guest behaviour",
      description:
        "Who buys late checkout? Which demographics convert best?",
    },
    {
      icon: Building2,
      title: "Portfolio roll-up",
      description:
        "Multi-property managers get group-wide and per-property stats.",
    },
    {
      icon: FileDown,
      title: "Exports",
      description:
        "Download CSVs or auto-email PDFs to stakeholders.",
    },
  ];

  const teams = [
    {
      icon: BarChart3,
      title: "Revenue managers",
      description:
        "Spot new upsell opportunities and measure uplift per booking.",
    },
    {
      icon: Megaphone,
      title: "Marketing leads",
      description: "Test subject lines and optimise flows.",
    },
    {
      icon: ClipboardList,
      title: "Ops managers",
      description: "Track fulfilment bottlenecks and response times.",
    },
    {
      icon: Briefcase,
      title: "Owners",
      description: "Get a simple, bottom-line view of ancillary growth.",
    },
  ];

  const cases = [
    {
      icon: BedDouble,
      title: "Hotel",
      description:
        "Adding late checkout to the T-24h email delivered +£9.80 per booking.",
    },
    {
      icon: UtensilsCrossed,
      title: "Restaurant",
      description: "Pre-arrival upsells doubled average basket size.",
    },
    {
      icon: Building2,
      title: "Venue",
      description:
        "Segmented sends boosted VIP upgrades 15% without extra marketing.",
    },
  ];

  return (
    <>
      <Navbar />
      <main className="pt-16 xs:pt-20 sm:pt-24">
        <PageHero
          title="Data That Pays for Itself"
          subtitle="EMS Insights shows you in real-time what's working and what isn't so you can double down on what converts."
        >
          <Button
            size="lg"
            className="w-full sm:w-auto rounded-full text-base bg-[#F65053] hover:bg-[#F65053]/90"
          >
            Get Started Free <ArrowUpRight className="h-5 w-5" />
          </Button>
          <Button
            variant="outline"
            size="lg"
            className="w-full sm:w-auto rounded-full text-base border-[#F65053] text-[#F65053]"
          >
            <CalendarDays className="h-5 w-5" /> Book a Demo
          </Button>
        </PageHero>

        <Section>
          <h2 className="text-3xl xs:text-4xl sm:text-5xl font-bold tracking-tight text-center">
            Why Insights Matter
          </h2>
          <div className="w-full max-w-screen-lg mx-auto mt-10 sm:mt-16 grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {why.map((item) => (
              <FeatureCard
                key={item.title}
                icon={item.icon}
                title={item.title}
                description={item.description}
              />
            ))}
          </div>
        </Section>

        <Section>
          <h2 className="text-3xl xs:text-4xl sm:text-5xl font-bold tracking-tight text-center">
            What You&apos;ll See
          </h2>
          <div className="w-full max-w-screen-lg mx-auto mt-10 sm:mt-16 grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {see.map((item) => (
              <FeatureCard
                key={item.title}
                icon={item.icon}
                title={item.title}
                description={item.description}
              />
            ))}
          </div>
        </Section>

        <Section>
          <h2 className="text-3xl xs:text-4xl sm:text-5xl font-bold tracking-tight text-center">
            How Teams Use Insights
          </h2>
          <div className="w-full max-w-screen-lg mx-auto mt-10 sm:mt-16 grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {teams.map((item) => (
              <FeatureCard
                key={item.title}
                icon={item.icon}
                title={item.title}
                description={item.description}
              />
            ))}
          </div>
        </Section>

        <Section>
          <h2 className="text-3xl xs:text-4xl sm:text-5xl font-bold tracking-tight text-center">
            Real Use Cases
          </h2>
          <div className="w-full max-w-screen-lg mx-auto mt-10 sm:mt-16 grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {cases.map((item) => (
              <FeatureCard
                key={item.title}
                icon={item.icon}
                title={item.title}
                description={item.description}
              />
            ))}
          </div>
        </Section>

        <Section>
          <div className="max-w-screen-md mx-auto text-center space-y-4">
            <p>
              Insights isn&apos;t just dashboards. It’s your feedback loop. Every
              email you send feeds data back into EMS, giving you a constantly
              improving revenue engine.
            </p>
            <p>
              If you can measure it, you can grow it. EMS Insights makes sure you
              do both.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4 pt-4">
              <Button
                size="lg"
                className="w-full sm:w-auto rounded-full text-base bg-[#F65053] hover:bg-[#F65053]/90"
              >
                Get Started Free <ArrowUpRight className="h-5 w-5" />
              </Button>
              <Button
                variant="outline"
                size="lg"
                className="w-full sm:w-auto rounded-full text-base border-[#F65053] text-[#F65053]"
              >
                <CalendarDays className="h-5 w-5" /> Book a Demo
              </Button>
            </div>
          </div>
        </Section>

        <Footer />
      </main>
    </>
  );
}

