import { Navbar } from "@/components/navbar";
import Footer from "@/components/footer";
import { Button } from "@/components/ui/button";
import { ArrowUpRight, CalendarDays } from "lucide-react";

export default function Page() {
  return (
    <>
      <Navbar />
      <main className="pt-16 xs:pt-20 sm:pt-24">
        <section className="max-w-screen-md mx-auto px-6 space-y-6">
          <h1 className="text-3xl font-semibold">Data That Pays for Itself</h1>
          <p>What’s working? What’s wasting inbox space? EMS Insights shows you in real-time—so you can double down on what converts and fix what doesn’t.</p>
          <h2 className="text-2xl font-semibold">Why Insights Matter</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>No guessing:</strong> Stop wondering which upsells work.</li>
            <li><strong>Prove ROI:</strong> Show stakeholders the revenue generated by each campaign.</li>
            <li><strong>Get better:</strong> Use data to refine your messaging and timing.</li>
          </ul>
          <h2 className="text-2xl font-semibold">What You’ll See</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Live revenue tracking:</strong> Know how much ancillary you’ve added today, this week, this month.</li>
            <li><strong>Email performance:</strong> Open rates, click-throughs, and conversions per automation.</li>
            <li><strong>Product insights:</strong> Identify your top-sellers and spot the duds.</li>
            <li><strong>Guest behaviour:</strong> Who buys late checkout? Which demographics convert best?</li>
            <li><strong>Portfolio roll-up:</strong> Multi-property managers get group-wide and per-property stats.</li>
            <li><strong>Exports:</strong> Download CSVs or auto-email PDFs to stakeholders weekly/monthly.</li>
          </ul>
          <h2 className="text-2xl font-semibold">How Teams Use Insights</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Revenue managers:</strong> Spot new upsell opportunities and measure uplift per booking.</li>
            <li><strong>Marketing leads:</strong> Test subject lines and optimise flows.</li>
            <li><strong>Ops managers:</strong> Track fulfilment bottlenecks and response times.</li>
            <li><strong>Owners:</strong> Get a simple, bottom-line view of ancillary growth.</li>
          </ul>
          <h2 className="text-2xl font-semibold">Real Use Cases</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Hotel:</strong> “We added late checkout to the T-24h email. It prints money. +£9.80 per booking on average.”</li>
            <li><strong>Restaurant:</strong> “Pre-arrival upsells doubled average basket size.”</li>
            <li><strong>Venue:</strong> “Segmented sends boosted VIP upgrades 15% without extra marketing.”</li>
          </ul>
          <h2 className="text-2xl font-semibold">Beyond Numbers</h2>
          <p>Insights isn’t just dashboards. It’s your feedback loop. Every email you send feeds data back into EMS, giving you a constantly improving revenue engine.</p>
          <p>If you can measure it, you can grow it. EMS Insights makes sure you do both.</p>
          <div className="flex flex-col sm:flex-row gap-4 pt-4">
            <Button size="lg" className="w-full sm:w-auto rounded-full text-base bg-[#F65053] hover:bg-[#F65053]/90">
              Get Started Free <ArrowUpRight className="h-5 w-5" />
            </Button>
            <Button variant="outline" size="lg" className="w-full sm:w-auto rounded-full text-base border-[#F65053] text-[#F65053]">
              <CalendarDays className="h-5 w-5" /> Book a Demo
            </Button>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

